### ISSUE TITLE
mcleaks support

### ISSUE THREAD

**Issue by MrGeorgen** [PrismarineJS/node-yggdrasil#47]
I would like to see mcleaks support in node-minecraft-protocol. I could add it, if you want. I'm not sure if this is outside of the scope this repo, so it maybe could be done in separate repo

**Comment by IdanHo** [comment]
This is not the appropriate package for this, since mcleaks has a different api, and the point of this package is to interact with the mojang api. What you can do though is make another package, that interacts with the mcleaks api, but has the same interface, and that way we can change node-minecraft-protocol to use either interchangeably

**Comment by MrGeorgen** [comment]
Yeah I can try to create package with the same interface, but I'm sure possible because the mcleaks api is very different
